### PR TITLE
fix sign of delta of release_memory tracer event

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Review by vyzo — COMMENTED** [review]
wait, it really is a negative delta!

**Comment by marten-seemann** [comment]
What does releasing a negative amount of memory mean? Does that mean we're reserving memory? :D

**Comment by vyzo** [comment]
Its more of a flat, contextless interpretation of delta, without looking at the event type.

So negative delta means release, positive means reserve.

Either way i dont feel particularly strongly about this ;)

**Comment by marten-seemann** [comment]
I'm going to merge this. I still find the minus sign confusing ;)

**Pull request merged**
