### PR TITLE
make service and protocol scope names distinguishable

### PR DESCRIPTION
**Pull request by marten-seemann**

### CODE REVIEW

**Review by vyzo — COMMENTED** [review]
isnt the prefix already there in the name?

**Comment by marten-seemann** [comment]
> isnt the prefix already there in the name?

I was getting entries like `libp2p.identity.peer:xyz` without this.

**Review by vyzo — APPROVED** [review]
ok then.

**Comment by marten-seemann** [comment]
That's weird. You're right, it should be in the scope name. Investigating what's going on here.

**Pull request closed without merging**
