### PR TITLE
metrics collection support

### PR DESCRIPTION
**Pull request by vyzo**
cc @travisperson @guseggert

### CODE REVIEW

**Comment by marten-seemann** [comment]
Is there a reason we're only providing access to `Block` events? Also, why can't users of this library not use a tracer to get access to these events?

**Comment by vyzo** [comment]
The current tracer writes to a file and it also a lot more low level than the high level actions we are tracking with the metrics object.
We could add custom tracer support (as an object), but it would still not get nice high level metrics as "service foo was blocked X times".

**Comment by vyzo** [comment]
Also, we are only tracking metrics for block events as these are the ones that are actually interesting from an operations point of view. Having a metrics that says "133713371337 memory reservations have been allowed" is not all that interesting.

**Comment by guseggert** [comment]
It's useful to know the proportion of reqs that are blocked since that's independent of host size (although maybe we can get the denominator elsewhere?).

**Comment by vyzo** [comment]
@guseggert you want Allow metrics as well? We can add this, just didn't think it would be all that useful.
@travisperson opinions on the matter?

**Comment by vyzo** [comment]
Added allow metrics.

**Pull request merged**
